export const professional = [
    {id: 1, name: "A2IM", url: "https://www.a2im.org", description: "The American Association of Independent Music (A2IM) is a 501(c)(6) not-for-profit trade organization that serves as a central voice for a diverse community of over 600 independently owned record labels operating within the United States. A2IM  represents their interests in the marketplace, in the media, on Capitol Hill, and as part of the global music community.", stack: ["Wordpress", "AWS Lightsail", "Elementor", "Cloudflare"]},
    {id: 2, name: "Libera Awards", url: "https://www.liberaawards.com", description: "U.S. based independent music awards site to provide updates each year on the status of each year’s community voting process, ticketing info, historical archives of previous winners, and a simple contact form.", stack: ['React', 'Nextjs', 'TypeScript', 'AWS Amplify', 'Strapi']},
    {id: 3, name: "Indie Week", url: "https://www.a2imindieweek.org", description: "An informational website built for an international music business conference.  You can find ticketing/lodging information, program scheduling, and sponsorship information.", stack: ['React', 'Nextjs', 'TypeScript', 'AWS Amplify', 'Strapi']},
    {id: 4, name: "Knowledge-base", url: "https://knowledge-base.a2im.org", description: "A knowledge-base website created for internal documentation & training used at The American Association of Independent Music (A2IM).  This site features full authentication protection at the domain level.", stack: ['React', 'Nextjs', 'TypeScript', 'AWS Amplify', 'Strapi']},
    {id: 5, name: "Headless CMS", url: "https://cms.a2im.org", description: "A headless CMS built for A2IM to supply media content to all web properties.  This server is built with AWS services such as EC2, DynamoDB, & S3.  The underlying framework used to build the server is Strapi.  Strapi is capable of  utilizing both RESTful & GraphQL API simultaneously.", stack: ['Strapi', 'AWS EC2', 'AWS RDS', 'NGINX']},
    {id: 6, name: "Artist Portfolio", url: "https://www.heidivf.com", description: "Artist Portfolio for Heidi Vasterling-Ford", stack: ['Squarespace']}
  ]

export const personal = [
    {id: 11, name: "WOBBLE.HOUSE", url: "https://wobble.house", description: "A personal project with some friends of mine", stack: ['React', 'Nextjs', 'TypeScript', 'AWS Amplify']},
    {id: 12, name: "Home Assistant", url: "https://www.github.com", description: "My Home Assistant is something I have built for my own home automation.", stack: ['OracleVM', 'HassOS', 'Frigate', 'Hue', 'Sonos']},
    {id: 14, name: "Discord+Slack Bots", url: "https://www.google.com", description: "I have created a few Discord bots", stack: ['AWS EC2', 'Python', 'Discord', 'Slack']},
  ]