export const professional = [
    {id: 1, title: "A2IM", url: "https://www.a2im.org", description: "The American Association of Independent Music (A2IM) is a 501(c)(6) not-for-profit trade organization that serves as a central voice for a diverse community of over 600 independently owned record labels operating within the United States. A2IM  represents their interests in the marketplace, in the media, on Capitol Hill, and as part of the global music community.", details: ["Wordpress", "AWS Lightsail", "Elementor", "Cloudflare"], img: {src: "/images/A2IM.jpg", alt:"screenshot of A2IM"}, urlvisit: true},
    {id: 2, title: "Libera Awards", url: "https://www.liberaawards.com", description: "U.S. based independent music awards site to provide updates each year on the status of each year’s community voting process, ticketing info, historical archives of previous winners, and a simple contact form.", details: ['React', 'Nextjs', 'TypeScript', 'AWS Amplify', 'Strapi'], img: {src: "/images/Libera+Awards.jpg", alt:"screenshot of Libera Awards"}, urlvisit: true},
    {id: 3, title: "Indie Week", url: "https://www.a2imindieweek.org", description: "An informational website built for an international music business conference.  You can find ticketing/lodging information, program scheduling, and sponsorship information.", details: ['React', 'Nextjs', 'TypeScript', 'AWS Amplify', 'Strapi'], img: {src: "/images/Indie+Week.jpg", alt:"screenshot of Indie Week"}, urlvisit: true},
    {id: 4, title: "Knowledge-base", url: "https://knowledge-base.a2im.org", description: "A knowledge-base website created for internal documentation & training used at The American Association of Independent Music (A2IM).  This site features full authentication protection at the domain level.", details: ['React', 'Nextjs', 'TypeScript', 'AWS Amplify', 'Strapi'], img: {src: "/images/Knowledge-base.jpg", alt:"screenshot of Knowledge-base"}, urlvisit: true},
    {id: 5, title: "Headless CMS", url: "https://cms.a2im.org", description: "A headless CMS built for A2IM to supply media content to all web properties.  This server is built with AWS services such as EC2, DynamoDB, & S3.  The underlying framework used to build the server is Strapi.  Strapi is capable of  utilizing both RESTful & GraphQL API simultaneously.", details: ['Strapi', 'AWS EC2', 'AWS RDS', 'NGINX'],img: {src: "/images/Headless+CMS.jpg", alt:"screenshot of Headless CMS"}, urlvisit: true},
    {id: 6, title: "Artist Portfolio", url: "https://www.heidivf.com", description: "Artist Portfolio for Heidi Vasterling-Ford", details: ['Squarespace'], img: {src: "/images/Artist+Portfolio.jpg", alt:"screenshot of Artist Portfolio"}, urlvisit: true}
  ]

export const personal = [
    {id: 11, title: "WOBBLE.HOUSE", url: "https://wobble.house", description: "A personal project with some friends of mine", details: ['React', 'Nextjs', 'TypeScript', 'AWS Amplify'], img: {src: "/images/WOBBLE.HOUSE.jpg", alt:"screenshot of WOBBLE.HOUSE",}, urlvisit: true},
    {id: 12, title: "Home Assistant", url: "https://www.github.com", description: "My Home Assistant is something I have built for my own home automation.", details: ['OracleVM', 'HassOS', 'Frigate', 'Hue', 'Sonos'], img: {src: "/images/Home+Assistant.jpg", alt:"screenshot of Home Assistant"}, urlvisit: true},
    {id: 14, title: "Discord+Slack Bots", url: "https://www.google.com", description: "I have created a few Discord bots", details: ['AWS EC2', 'Python', 'Discord', 'Slack'], img: {src: "/images/Discord+Slack+Bots.jpg", alt:"screenshot of Discord+Slack+Bots"}, urlvisit: true},
  ]